version: 2.1

commands:
  build-and-test:
    steps:
      - checkout
      - run: chmod +x gradlew
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # run tests!
      - run: ./gradlew clean check jacocoTestReport --continue --console=plain
      - run:
          name: Upload Coverage
          when: on_success
          command: bash <(curl -s https://codecov.io/bash) -Z -C $CIRCLE_SHA1
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}
  run-api-diff:
    steps:
      - run: chmod +x gradlew
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      # run apiDiff task
      - run: ./gradlew clean apiDiff
      - store_artifacts:
         path: build/reports/apiDiff/apiDiff.txt
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "build.gradle" }}

jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    steps:
      - build-and-test
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      TERM: dumb
  api-diff:
    docker:
      - image: openjdk:8-jdk
    steps:
      - run-api-diff
    environment:
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"'
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"
      TERM: dumb

workflows:
  build-and-test:
    jobs:
      - build
  api-diff:
    jobs:
      - api-diff
